language: elixir
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.3.1
    - elixir: 1.6.6
      otp_release: 20.3.1
    - elixir: 1.7.0
      otp_release: 21.0.3
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
